### ISSUE TITLE
about MS-TCN++

### ISSUE THREAD

**Issue by MichaelHL-ai** [ShangHua-Gao/G2L-search#1]
hi, thank u for your awesome work. I wonder how to applying G2L to MS-TCN++ receptive field search, because MS-TCN++ have DDL module

**Comment by Hanqer** [comment]
I wonder what the meaning of DDL module? Do you mean the 'pyc' files of something? We modify the official code of MS-TCN++, to conduct the EGI local search.

**Comment by MichaelHL-ai** [comment]
> I wonder what the meaning of DDL module? Do you mean the 'pyc' files of something? We modify the official code of MS-TCN++, to conduct the EGI local search.

Oh, I see. DDL( Dual Dilated Layer) has at least two dilation convs. Global search didn't apply to MS-TCN++, So MS-TCN++ global search result was origin MS-TCN++?

**Comment by Hanqer** [comment]
Yes, it was the original MS-TCN++ structure.

**Comment by MichaelHL-ai** [comment]
thx
