### ISSUE TITLE
how long did you train?

### ISSUE THREAD

**Issue by MichaelHL-ai** [ShangHua-Gao/G2L-search#2]
hi, it's me again. Though you reduce searching params, but you have to run like 5 epochs each structure. I wonder how long you spent to get final model params.

**Comment by Hanqer** [comment]
We run the global search on 8*RTX 2080Ti GPUs, and it takes about 42 hours on the BreakFast dataset.

**Comment by MichaelHL-ai** [comment]
> We run the global search on 8*RTX 2080Ti GPUs, and it takes about 42 hours on the BreakFast dataset.

What about the local search time?

**Comment by Hanqer** [comment]
It only takes about 3 ~ 4 hours of local search on BreakFast dataset with a single GPU.

**Comment by MichaelHL-ai** [comment]
got it! thx!
