### ISSUE TITLE
Can searched receptive field model finetune from pretrained weight or from scratch?

### ISSUE THREAD

**Issue by Haijunlv** [ShangHua-Gao/G2L-search#4]
Thanks your wonderful work and code.
Searching efficient receptive field is such a interesting topic!
I have one question. can searched receptive field model finetune from pretrained weight or from scratch?
If i have a faster rcnn pretrain model from  https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_fpn_2x_coco.py.
The pretrain ap is 38.4.
Now i use rfnext to search.
First search phase. I have two choice.
  1. search from scratch
  2. search from pretrain faster_rcnn_r50_fpn_2x_coco weight
Which one is prefer?

After search, I have got a new search model.. I have two finetune choice
1. finetune from scratch
2. finetuen from pretrain faster_rcnn_r50_fpn_2x_coco weight.
Which one is prefer?

For my view, reuse pretrain weight is better. But i donot know if it will harm ap.

**Comment by gasvn** [comment]
During searching and retraining, we train the model with only imagenet pretrained weights. We didn't try if load a coco pretrained model would be better or not. But I think load a coco pretained weights mostly likely achieves better performance because it is similar to train with more epochs.

**Comment by gasvn** [comment]
We are looking forward to your results if you are trying to train from a coco preatrained model.

**Comment by Haijunlv** [comment]
ok, i will report result when i test rfnext code
